### ISSUE TITLE
Sharing some of my own Cisco knowledge

### ISSUE THREAD

**Issue by tomstorey** [tomverbeure/cisco-vwic3-2mft#1]
Hi, you might find some information that I have discovered in some recent reverse engineering projects useful: https://github.com/tomstorey/c1600re

In particular the pinout for a traditional WIC slot - data and address busses, control signals etc

Maybe some of this information translates over to HWIC, since I believe HWIC slots can also accept older WIC cards as well.

I made a WIC breakout board that presents all of the signals on some headers, you can find gerbers and design files in my repo.

**Comment by tomverbeure** [comment]
Info added to README. 

Thanks!
Tom
